name: Test Building Blocks repository

# Short abstract for this collection (optional)
abstract: |
  Temporary repository for testing OGC building block construction 2025-10-20

# Description for this collection (optional)
description: |
  Try creating simple building block for metadata 'Agent' element that implements
  content of ISO19115-3 responsble party, a person or organization in a role with a 
  point of contact. Person may have an affiliation with an organization.

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.bbr.test.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: False

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
#   resources:                              # Additional resources to upload apart from building block metadata
#      ontologies: true                     #   Whether to upload ontology files to the triplestore
