$schema: https://json-schema.org/draft/2020-12/schema
description: Agent entity; can be person, organization or (person or Organization) with Role. The third option is represented using schema.org contributor
$definitions:
  Person:
    type: object
    properties:
      $ref: ../../properties/person/schema.yaml
  Organization:
    type: object
    properties:
      $ref: ../../properties/organization/schema.yaml
  AgentInRole:
    type: object
    properties:
      $ref: ../../properties/agentInRole/schema.yaml
anyOf:
  - $ref: '#/$definitions/Person'
  - $ref: '#/$definitions/Organization'
  - $ref: '#/$definitions/AgentInRole'