$schema: https://json-schema.org/draft/2020-12/schema
description: Agent entity; can be person, organization or (person or Organization) with Role. The third option is represented using schema.org contributor
$definitions:
  Person:
    type: object
    properties:
      $ref: ../../properties/person/schema.yaml
# add organization and contributor incrementally
allOf:
  - $ref: '#/$definitions/Person'